const CONFIG = {
    CANVAS_WIDTH: window.innerWidth,
    CANVAS_HEIGHT: window.innerHeight,
    PLAYER_SPEED: 0.1,
    BULLET_SPEED: 0.2,
    BULLET_SIZE: 0.1,
    FIRE_RATE: 150,
    ENEMY_SPAWN_INTERVAL: 2000,
    SQUARE_ENEMY_SCORE_THRESHOLD: 500,
    INITIAL_ENEMY_POOL_SIZE: 20,
    INITIAL_BULLET_POOL_SIZE: 50
};