const CONFIG = {
    CANVAS_WIDTH: 800,
    CANVAS_HEIGHT: 600,
    PLAYER_SPEED: 5,
    BULLET_SPEED: 10,
    BULLET_SIZE: 12,
    BULLET_THICKNESS: 4,
    FIRE_RATE: 150,
    ENEMY_SPAWN_INTERVAL: 2000,
    SQUARE_ENEMY_SCORE_THRESHOLD: 500
};